In [2]:
import numpy as np

In [4]:
#Q1
arr = np.random.randint(1, 21, size=(3, 3))
arr

array([[ 5, 13,  7],
       [18,  9,  5],
       [ 7,  5, 13]])

In [6]:
#Q2
arr2 = np.random.randint(1, 21, size=(5, 5))
arr2

array([[19,  4,  1, 13, 11],
       [20,  3, 19, 15, 13],
       [ 9, 20,  6,  2,  2],
       [17,  1,  9, 14, 16],
       [ 9,  9, 10, 10,  9]])

In [8]:
arr2.min()

1

In [10]:
arr2.max()

20

In [42]:
#Q3
vector1 = np.random.randint(10)
vector

array([ 1,  1,  2,  2,  3,  4,  5,  6,  9, 10])

In [48]:
np.sort(vector)

array([ 1,  1,  2,  2,  3,  4,  5,  6,  9, 10])

In [56]:
#Q4
arr3=np.array([
    (3,5,7),(5,7,8),
    (99,88,77),(55,44,70)
])
arr3

array([[ 3,  5,  7],
       [ 5,  7,  8],
       [99, 88, 77],
       [55, 44, 70]])

In [62]:
arr3.argmax()

6

In [64]:
#Q5
arr= np.array([(2,4,5) ,(5,7,8)])
arr

array([[2, 4, 5],
       [5, 7, 8]])

In [68]:
arr[arr% 2 == 0] = 0
arr

array([[0, 0, 5],
       [5, 7, 0]])

In [72]:
#Q6
arr1=np.array([3,7,5])
arr1

array([3, 7, 5])

In [74]:
np.sqrt(arr1)

array([1.73205081, 2.64575131, 2.23606798])

In [102]:
#q7
arr= np.random.rand(3,3)
arr.mean(axis=1, keepdims=True)
arr.mean

<function ndarray.mean>

In [104]:
#q8
arr=np.array([1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39])
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [110]:
#q9
array_5x5 = np.random.rand(5, 5)
np.sort(array_5x5, axis=0)[-2, :]

array([0.80327106, 0.71476348, 0.69387018, 0.94318596, 0.86170161])

In [114]:
#Q10
array_4x4 = np.random.rand(4, 4)
np.sum(array_4x4, axis=1)

array([1.60495279, 2.13245578, 1.53579764, 1.28961239])